### ISSUE TITLE
emacs from the copr repo fails to run on Fedora 33

### ISSUE THREAD

**Issue by jose-matos** [A6GibKm/emacs-pgtk-nativecomp-copr#2]
Installing from the copr on Fedora 33 install without any issue.

The problem happens when running it. It takes all the memory in the computer (32 GB).
I see that emacs spawns lots of instances that refer trampoline and "delete char".

Fortunately oomd-early memory kicks in but it kill almost all processes except for emacs.
All processors are busy with the emacs processes.

Such as it is I am not able to run emacs. :-(

**Comment by A6GibKm** [comment]
I am closing as f33 is EOL. Please reopen and edit the name if the issue persists.
