### ISSUE TITLE
Create builds for Fedora 34

### ISSUE THREAD

**Issue by sebasmonia** [A6GibKm/emacs-pgtk-nativecomp-copr#4]
Fedora 34 beta is out!

Would be nice to get builds rolling for it :)

Thank you for your work on this, it is great to have gtk + native in one easy to install package.

**Comment by A6GibKm** [comment]
I am sorry I did not notice this, a build should be out soon^tm.  I enabled the builds but I did not update the commit, therefore nothing was built.

**Comment by sebasmonia** [comment]
Once again thank you for your work!
