### ISSUE TITLE
Please bump source commit

### ISSUE THREAD

**Issue by truls** [A6GibKm/emacs-pgtk-nativecomp-copr#7]
Hi,

First of all, thanks a lot for your work setting up and maintaining this COPR repo!

The most recent COPR build isn't working for me. When runing `emacs -Q` the GUI doesn't show up and it instead opens a terminal window that seems to go into an infinite loop loading some files.

I just tried building the RPMs locally from the most recent flatwhatson/emacs commit (b94a57e4856e94444606f86a5ee18c5acfca34ec) and it works fine. Could you please bump the COPR packages to that commit?

Truls

**Comment by A6GibKm** [comment]
We updated recently.
